[Feature] View Only Link documentation [OSF-7470]
caseyrollins/swagger-ui pull request #48
Opened 2017-03-21 16:02 UTC by fabmiz

Purpose

Add view only link (VOL) endpoints documentation to the new API docs.

Changes

Adds model definition and yaml spec files for endpoints /view_only_links/<link_id>/ (detail.yaml)
/view_only_links/nodes/ (nodes_list.yaml).

Ticket

https://openscience.atlassian.net/browse/OSF-7470

2017-03-22 18:17 UTC, caseyrollins requested changes
First pass done. Looking good so far, just various language changes to make and some adjusting of the definition file. 🌮

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/definition.yaml
> +    description: 'The type identifier of the view only link.'
"The type identifier of the view only link ('view-only-links')."

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/definition.yaml
> +    description: 'The identifier of the view only link.'
"The unique identifier of the view only link."

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/definition.yaml
> +        description: 'The time at which the view only link was created'
For consistency: "The time at which the view only link was created, as an iso8601 formatted timestamp."

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/definition.yaml
> +      anonymous:
I'm pretty sure a `default` key can be added here (although I don't think we use it anywhere else ATM). Can you try it out?
```
anonymous:
    type: boolean
    default: true
    readOnly: true
    description: '...'
```

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/nodes.yaml
> +    This request should never return an error.
This request actually can return an error, especially if you're requesting a VOL that doesn't exist or if you don't have administrator permissions.

In general  this statement is only true for top-level API endpoints (like `/v2/nodes/`, `/v2/users/`, `/v2/registrations/`, `/v2/preprints/`, etc).

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/nodes.yaml
> +    #### Filtering
Filtering on this endpoint doesn't currently work, and I'm not convinced this endpoint even needs filtering, so let's remove this section.

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/nodes.yaml
> +      examples:
In general, I prefer that the example responses are good examples of projects on the OSF. For an example node response I've been using projects such as:
- RPP (https://osf.io/ezcuj, https://api.osf.io/v2/nodes/ezcuj) 
- RP:CB (https://osf.io/e81xl, https://api.osf.io/v2/nodes/e81xl)
- TOP Guidelines (https://osf.io/9f6gx, https://api.osf.io/v2/nodes/9f6gx)

Pick your favorite and go with that.

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/definition.yaml
> +required:
It appears I was wrong about both the required situation and how VOLs can be updated. 

From the [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13) (see the `readOnly` section):

> Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but MUST NOT be sent as part of the request. Properties marked as readOnly being true SHOULD NOT be in the required list of the defined schema. Default value is false.

Additionally, view only links can be created/updated from the `/nodes/<node_id>/view_only_links/` endpoint (serializer [here](https://github.com/CenterForOpenScience/osf.io/blob/develop/api/nodes/serializers.py#L1214)). Writeable fields include the `anonymous` and `name` attributes, and the `nodes` relationship.

Can you update the definition appropriately to reflect this?

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/definition.yaml
> +      name:
If the `default` key mentioned above works, the `name` property should have a default value of "Shared project link".

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/definition.yaml
> +        description: 'A relationship to the nodes affiliated with this view only link.'
Possibly more clear: "A relationship to the nodes which this view only link gives read-only access to."

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/detail.yaml
> +        View only links on a node, public or private, are only readable and
To be more consistent with [nodes](https://github.com/CenterForOpenScience/developer.osf.io/blob/develop/swagger-spec/nodes/detail.yaml#L8): "Only project administrators may retrieve the details of a view only link. Attempting to retrieve a view only link without appropriate permissions will result in a 403 Forbidden response."

2017-03-22 18:17 UTC, caseyrollins commented on swagger-spec/view_only_links/nodes.yaml
> +    This requires admin permissions on all nodes to be associated with this view only link.
Same as above comment: "Only project administrators may retrieve the nodes of a view only link. Attempting to retrieve a view only link without appropriate permissions will result in a 403 Forbidden response."

2017-03-22 20:11 UTC, fabmiz commented on swagger-spec/view_only_links/definition.yaml
> +    description: 'The identifier of the view only link.'
Done.

2017-03-22 20:12 UTC, fabmiz commented on swagger-spec/view_only_links/definition.yaml
> +    description: 'The type identifier of the view only link.'
Done.

2017-03-22 20:13 UTC, fabmiz commented on swagger-spec/view_only_links/definition.yaml
> +        description: 'The time at which the view only link was created'
Done.

2017-03-22 20:13 UTC, fabmiz commented on swagger-spec/view_only_links/definition.yaml
> +      anonymous:
Done. Yes, the default key can be added.

2017-03-22 20:13 UTC, fabmiz commented on swagger-spec/view_only_links/definition.yaml
> +      name:
Done.

2017-03-22 20:14 UTC, fabmiz commented on swagger-spec/view_only_links/definition.yaml
> +        description: 'A relationship to the nodes affiliated with this view only link.'
Done.

2017-03-22 20:14 UTC, fabmiz commented on swagger-spec/view_only_links/nodes.yaml
> +    This requires admin permissions on all nodes to be associated with this view only link.
Done.

2017-03-22 20:14 UTC, fabmiz commented on swagger-spec/view_only_links/nodes.yaml
> +    #### Filtering
Ok. Got it!

2017-03-22 20:14 UTC, fabmiz commented on swagger-spec/view_only_links/detail.yaml
> +        View only links on a node, public or private, are only readable and
Done.

2017-03-22 20:29 UTC, fabmiz commented on swagger-spec/view_only_links/nodes.yaml
> +      examples:
Done. great time saver!!

2017-03-22 20:55 UTC, fabmiz commented on swagger-spec/view_only_links/definition.yaml
> +required:
Got it. Done!!

2017-03-28 15:55 UTC, caseyrollins requested changes
One minor change and this is RTM.

2017-03-28 15:55 UTC, caseyrollins commented on swagger-spec/view_only_links/nodes.yaml
> +    A list of nodes associated with the View Only Link.
I think the description from the definition might be better here: "The list of nodes which this view only link gives read-only access to."

2017-03-28 20:16 UTC, caseyrollins approved these changes
🎉 🌮 🎉

2017-03-31 15:34 UTC, merged