[Feature] Add metaschema model definition, list and detail endpoints [OSF-7457]
caseyrollins/swagger-ui pull request #50
Opened 2017-03-28 15:17 UTC by fabmiz

#### Purpose

Add documentation for metaschemas endpoints.

#### Changes

- Creates metaschemas model definition.
- Adds metaschemas detail endpoint (/metaschemas/<metaschema_id>/ ) documentation (detail.yaml).
- Adds metaschemas list endpoint (/metaschemas/) documentation (listl.yaml).

#### Ticket
- [OSF-7457](https://openscience.atlassian.net/browse/OSF-7457)

2017-03-29 17:16 UTC, caseyrollins requested changes
A few questions and changes needed, but this is looking great :octocat:

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/list.yaml
> +  responses:
In the interest of the example response section not being ridiculously long (at least until we have scrolling in that section of the docs) can you limit this response to maybe just the simplest metaschema? I think that would be either the "Open-ended Registration" or "OSF-Standard Pre-Data Collection Registration" metaschema.

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/definition.yaml
> +    readOnly: false
Attributes should be `readOnly: true`

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/definition.yaml
> +        description: 'Name of the registration schema'
"The name of the metaschema."

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/definition.yaml
> +        description: 'Latest version of the schema'
"The latest version of the metaschema."

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/definition.yaml
> +        description: 'Registration schema details'
"The details of the metaschema which contain the supplemental questions to accompany a registration."

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/definition.yaml
> +    description: 'URLs to alternative representations of the user entity.'
"URLs to alternative representations of the metaschema entity."

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/definition.yaml
> +        additionalProperties:
What is the `additionalProperties` key here specifying?

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/metaschemas/definition.yaml
> +        type: object
Object means the same thing in this context, so this is fine 👍

2017-03-29 17:16 UTC, caseyrollins commented on swagger-spec/swagger.yaml
> +  #   METASCHEMAS   #
Can you make sure that this file stays in alphabetical order? The metaschemas URLs should be between institutions and nodes here.

2017-03-30 13:24 UTC, fabmiz commented on swagger-spec/metaschemas/definition.yaml
> +    readOnly: false
Ok. Got it!

2017-03-30 13:24 UTC, fabmiz commented on swagger-spec/metaschemas/definition.yaml
> +        description: 'Name of the registration schema'
Done.

2017-03-30 13:24 UTC, fabmiz commented on swagger-spec/metaschemas/definition.yaml
> +        description: 'Latest version of the schema'
Done.

2017-03-30 13:32 UTC, fabmiz commented on swagger-spec/metaschemas/definition.yaml
> +        additionalProperties:
Swagger UI does not seem to have a way to represent dictionaries. So this defines a dictionary where the values are arrays of strings.

2017-03-30 13:40 UTC, fabmiz commented on swagger-spec/metaschemas/list.yaml
> +  responses:
Go it. Done.

2017-03-31 15:32 UTC, caseyrollins approved these changes
💯

2017-03-31 15:37 UTC, merged