[WIP] Comments [OSF-7450]
caseyrollins/swagger-ui pull request #6
Opened 2017-02-13 21:54 UTC by alexschiller

[WIP] as I'll do one final pass in the morning to ensure I caught all the things I wanted to change.
Add comments route (commented out reports for the time being)

[#OSF-7450]
https://openscience.atlassian.net/browse/OSF-7450

2017-02-14 19:06 UTC, caseyrollins requested changes
Looks good, just very minor language changes to be made on various descriptions. 🦄 

Also, can you do a sanity check that `swagger validate` doesn't throw any errors on this branch?

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/definition.yaml
> +        description: Can the current user edit this comment?
For all of the boolean properties in this definition, can you keep the descriptions consistent and following the form "Whether or not ..." (e.g. "Whether or not the current user has permission to edit this comment")?

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/definition.yaml
> +        description: What page type is this comment on?
Can this description be improved? I'm still not sure what the page property means after reading it. Possibly add example page types?

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/definition.yaml
> +        description: 'The URL representation of the node the comment''s node'
> The URL representation of the node the comment's node

The property descriptions in this section don't really make sense...

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/detail.yaml
> +  summary: Modify a comment
"Update a comment"

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/detail.yaml
> +      description: 'The unique identifier of the comment you wish to modify.'
"The unique identifier of the comment you wish to update."

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/detail.yaml
> +            id: twpgrpv78d8s
I would change this to `{comment_id}` since it's an example payload.

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/detail.yaml
> +    Deletes a comment. This action can be undone by issuing a PUT request against the /links/self URL, setting `deleted` to `False`.
"Deletes a comment. This action can be undone by setting `deleted` to `False` in a comment update request."

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/report_detail.yaml
>  # /comments/{comment_id}/reports/{user_id}/
Note to self: purposely not reviewing since this endpoint is commented out in swagger.yaml ATM.

2017-02-14 19:06 UTC, caseyrollins commented on swagger-spec/comments/reports_list.yaml
>  # /comments/{comment_id}/reports/
Note to self: purposely not reviewing since this endpoint is commented out in swagger.yaml ATM.

2017-02-14 20:02 UTC, alexschiller commented on swagger-spec/comments/definition.yaml
> +        description: 'The URL representation of the node the comment''s node'
Pretty sure I a word or or three

2017-02-16 14:39 UTC, caseyrollins approved these changes

2017-02-16 14:39 UTC, caseyrollins commented
🎉  🦄  🎉

2017-02-16 14:39 UTC, merged