[WIP] Files [OSF-7451]
caseyrollins/swagger-ui pull request #8
Opened 2017-02-15 21:40 UTC by alexschiller

Add files routes

[#OSF-7451]
https://openscience.atlassian.net/browse/OSF-7451

2017-02-15 22:31 UTC, caseyrollins commented on swagger-spec/files/version_detail.yaml
> +          $ref: 'version_definition.yaml'
Where's `version_definition.yaml`?

2017-02-15 22:53 UTC, alexschiller commented on swagger-spec/files/version_detail.yaml
> +          $ref: 'version_definition.yaml'
That's why it is a WIP pr :). Was multitasking and missed it. Added.

2017-02-17 15:23 UTC, caseyrollins requested changes
This looks great! A few extremely minor changes and this will be RTM. 🦄

2017-02-17 15:23 UTC, caseyrollins commented on swagger-spec/files/definition.yaml
> +      tags:
The tags property can actually be:
```
tags:
  type: array
  items: 
    type: string
  description: ''
```

2017-02-17 15:23 UTC, caseyrollins commented on swagger-spec/files/definition.yaml
> +    description: ''
'URLs to other entities or entity collections that have a relationship to the file entity.'

2017-02-17 15:23 UTC, caseyrollins commented on swagger-spec/files/versions_list.yaml
> +  summary: Retrieve file versions
"List all file versions"

I've been inconsistent about this (sorry), but I think I've fixed it everywhere now. List views should use "List..." and detail views should use "Retrieve..."

2017-02-17 15:23 UTC, caseyrollins commented on swagger-spec/institutions/definition.yaml
> +    description: The type identifier of the institution entity (`institutions`).
👍

2017-02-17 20:58 UTC, caseyrollins approved these changes

2017-02-17 21:00 UTC, merged